### ISSUE TITLE
NodeJS throws a `secure crypto unusable, insecure Math.random not allowed` error

### ISSUE THREAD

**Issue by Bricklou** [thompsonsj/slate-serializers#147]
I'm using the library inside a React Inertia project with server-side rendering, but i get the following error when trying to render the `<SlateToReact />` component:
```
[09:31:43.471] ERROR (11326): secure crypto unusable, insecure Math.random not allowed
    request_id: "zfqx8bkyz5797njolcbra6dl"
    x-request-id: "zfqx8bkyz5797njolcbra6dl"
    err: {
      "type": "Error",
      "message": "secure crypto unusable, insecure Math.random not allowed",
      "stack":
          Error: secure crypto unusable, insecure Math.random not allowed
              at createError (file:///.../node_modules/.pnpm/@slate-serializers+react@2.1.6/node_modules/@slate-serializers/react/index.esm.js:1203:15)
              at detectPrng (file:///.../node_modules/.pnpm/@slate-serializers+react@2.1.6/node_modules/@slate-serializers/react/index.esm.js:1280:11)
              at factory (file:///.../node_modules/.pnpm/@slate-serializers+react@2.1.6/node_modules/@slate-serializers/react/index.esm.js:1284:20)
              at file:///.../node_modules/.pnpm/@slate-serializers+react@2.1.6/node_modules/@slate-serializers/react/index.esm.js:1293:12
```

I'm running on NodeJS 22.

I did some digging and it seems `slate-serializers` use `ulid` but this library hasn't been updated since 6 years already. There are obviously some forks like [`ulidx`](https://www.npmjs.com/package/ulidx), but it needs some testing.

**Comment by thompsonsj** [comment]
Thanks @Bricklou ! Also appreciate the suggestion of a library to replace it with - tests pass with [this replacement](https://github.com/thompsonsj/slate-serializers/pull/153) so I am happy!
